### ISSUE TITLE
mys-config nor pkg-config found

### ISSUE THREAD

**Issue by s14k51** [mys-lang/mys#52]
**What did you do?**

I followed the [Getting started](https://mys-lang.org/user-guide/getting-started.html) section, installed mys, created a new package (the default hello-world template), and ran `mys run` (I did not even touch any files in the package), and got a `mys-config nor pkg-config found` message instead of the print output. By the way, the mys installation did create a `~/.config/mys/config.toml`, and it is empty.

**What did you expect to see?**

```
$ mys run
 ✔ Reading package configuration (... seconds)
 ✔ Downloading dependencies (... seconds)
 ✔ Building (... seconds)
Hello, world!
```

**What did you see instead?**

```
$ mys run
 ✔ Reading package configuration (... seconds)
 ✔ Downloading dependencies (... seconds)
mys-config nor pkg-config found
```

**Mys version**

0.342.0

**Comment by s14k51** [comment]
`mys build` also shows the same output

**Comment by eerimoq** [comment]
What OS are you using?

**Comment by s14k51** [comment]
MacOS Monterey. I also have xcode tools installed.

**Comment by s14k51** [comment]
My issue is resolved by installing `pkg-config`.
